core/blog/api/v1/urls.py
from django.urls import path,include
from . import views

app_name = 'api-v1'

urlpatterns = [
    # 1. API function base view (FBV)
    # path('posts/', views.postList, name='post_list'),   
    # path('post/<int:pk>/', views.postDetail, name='post_detail'),
    
    # 2. APIView in CBV
    # path('posts/', views.PostList.as_view(), name='post_list'),
    # path('post/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    
    
    # 3. GenericAPIView in CBV
    # path('posts/', views.PostListCreateAPIView.as_view(), name='post_list'),
    # path('post/<int:pk>/', views.PostRetrieveUpdateDestroyAPIView.as_view(), name='post_detail'),
    
    
    # 4. ModelViewSet in CBV
    # 4.1 viewsets.ViewSet
    # path('posts/', views.PostViewSet.as_view({'get':'list','post':'create'}), name='post_list'),
    # path('posts/<int:pk>', views.PostViewSet.as_view({'get':'retrieve','put':'update','patch':'partial_update','delete':'destroy'}), name='post_list'),
        
]


    # 4.2 viewsets.ModelViewSet
from rest_framework.routers import DefaultRouter
router = DefaultRouter()
# router.register('posts', views.PostViewSet, basename='post')
router.register('posts', views.PostModelViewSet, basename='post')
router.register('categories', views.CategoryModelViewSet, basename='category')
router.register('comments', views.PostCommentModelViewSet, basename='comment')
urlpatterns += router.urls
'''
urlpatterns += [
    path('',include(router.urls)),
]
'''

core/blog/urls.py
from django.urls import path,include
# from .views import api_task_list_view
from . import views
from rest_framework.routers import DefaultRouter

app_name = 'blog'

router = DefaultRouter()
# router.register('blog', views.BlogModelViewSet, basename='blog')



urlpatterns = [
    # path('task/', views.api_task_list_view,name='api-task-list'),
    # path('task/', views.TaskList, name='task-list'),
    # path('task/', views.TaskList.as_view(), name='task-list'),
    # path('task/<int:id>/', views.taskDetail, name='task-detail'),
    # path('task/<int:pk>/', views.TaskDetail.as_view(), name='task-detail'),
    # path('task/', views.TaskViewSet.as_view({'get':'list','post':'create'}), name='task-list'),
    # path('task/<int:pk>/', views.TaskViewSet.as_view({'get':'retrieve','put':'update','patch':'partial_update','delete':'destroy'}), name='task-list'),
]

urlpatterns += router.urls

urlpatterns += [
    path('posts/', views.PostListView.as_view(), name='post_list'),
    path('post/<int:pk>/', views.PostDetailView.as_view() ,name='post-detail'),
    # path('comment/<int:pk>/', views.PostCommentView.as_view(), name='post-comment'),
    
    # path('redirect<int:pk>/', views.RedirecttoPostSingleView.as_view(), name='redirect'),
    path('create/', views.PostCreateView.as_view(), name='post-create'),
    path('edit/<int:pk>/', views.PostUpdateView.as_view(), name='post-update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='post-delete'),

    
    path('api/v1/',include('blog.api.v1.urls')),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('api-auth/', include('rest_framework.urls')),
    
    
    # apps in project
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
    
    # api docs  
    path('api-docs/',include_docs_urls(title='api sample')),    

]

# when DEBUG is True, serve media & static files for development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

   
# docs Swagger and Redoc
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="itmeter API",
      default_version='v1',
      description="The description of ToDo CBV project",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="poorya189@gmail.com"),
      license=openapi.License(name="MIT License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns += [    
    path('swagger/output.json', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

core/blog/models.py
from django.db import models
# from django.conf import settings
# from django.contrib.auth import get_user_model
# from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
 
# User = get_user_model()

        
        
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from accounts.models import Profile,User
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name
    
    
class Post(models.Model):
    # image = models.ImageField(upload_to='blog/%Y/%m/%d/',default='blog/defaultPost.jpg')
    image = models.ImageField(upload_to='blog/%Y/%m/%d/',null=True, blank=True)
    #author = models.ForeignKey(User, on_delete=models.CASCADE)
    author = models.ForeignKey('accounts.Profile', on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=255)
    topic = models.ForeignKey('homepage.Topic', on_delete=models.SET_NULL, null=True)
    content = models.TextField()
    tags = TaggableManager()
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
    counted_views = models.IntegerField(default=0) # default=0
    status = models.BooleanField(default=False)
    login_require = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ('-created_date',)
        #verbose_name = "پست"
        #verbose_name_plural = "پست ها"
    def __str__(self):
        return f'{self.title} - {self.id}'

    def get_snippet(self):
        return self.content[:10]+'...'
    
    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'post_id':self.id})
    
    def get_relative_api_url(self):
        return reverse('blog:api-v1:post-detail', kwargs={'pk':self.id})
    
    def increment_views(self):
        self.counted_views += 1
        self.save(update_fields=['counted_views'])
    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        return None 
    

class PostComment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)  # Link to Profile
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # Link to User model
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.profile.first_name} {self.profile.last_name} - post: {self.post}'

    class Meta:
        ordering = ('-created_date',)

core/accounts/forms.py
#from itmeter
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

core/blog/api/v1/views.py
from rest_framework.decorators import api_view,permission_classes
from rest_framework.permissions import (IsAdminUser, IsAuthenticated,
                                        IsAuthenticatedOrReadOnly,)
from rest_framework.response import Response
from rest_framework import status
from django.shortcuts import get_object_or_404
from .serializers import PostSerializer, CategorySerializer,PostCommentSerializer
from ...models import Post,Category,PostComment


# 1. API function base view (FBV)
"""
@api_view(['GET','POST'])
@permission_classes([IsAuthenticatedOrReadOnly])
def postList(request):
    if request.method == 'GET':
        posts = Post.objects.all()
        serializer = PostSerializer(posts, many=True)
        return Response(serializer.data)
    elif request.method == 'POST':
        serializer = PostSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data,status=status.HTTP_201_CREATED)
    

@api_view(['GET','PUT','DELETE'])
@permission_classes([IsAuthenticatedOrReadOnly])
def postDetail(request,pk):
    post = get_object_or_404(Post, pk=pk, status=True)    
    if request.method == 'GET':
        serializer = PostSerializer(post)
        return Response(serializer.data)
    elif request.method == 'PUT':
        serializer = PostSerializer(post,data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)
    elif request.method == 'DELETE':
        post.delete()
        return Response({'details':'The item successfully deleted.'},status=status.HTTP_204_NO_CONTENT)
"""    
    
 

from rest_framework.permissions import (IsAdminUser, IsAuthenticated,IsAuthenticatedOrReadOnly,)
from rest_framework.views import APIView

# 2. APIView in CBV
"""
class PostList(APIView):
    permission_classes = [IsAuthenticatedOrReadOnly]
    serializer_class = PostSerializer
    def get(self,request):
        posts = Post.objects.filter(status=True)
        serializer = PostSerializer(posts, many=True)
        return Response(serializer.data)
    
    def post(self,request):
        serializer = PostSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data,status=status.HTTP_201_CREATED)
    

class PostDetail(APIView):
    permission_classes = [IsAuthenticatedOrReadOnly]
    serializer_class = PostSerializer
        
    '''retriving'''
    '''
    def get_object(self,pk):
        post = get_object_or_404(Post, pk=pk, status=True)
        return post
    '''
        
    '''retriving'''
    def get(self,request,pk):
        # post = self.get_object(pk)
        post = get_object_or_404(Post, pk=pk, status=True)
        # serializer = PostSerializer(post)
        serializer = self.serializer_class(post)
        return Response(serializer.data)
    
    '''editing'''
    def put(self,request,pk):
        post = get_object_or_404(Post, pk=pk, status=True)
        serializer = PostSerializer(post,data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)
    
    '''deleting'''
    def delete(self,request,pk):
        post = get_object_or_404(Post, pk=pk, status=True)
        post.delete()
        return Response({'details':'The item successfully deleted.'},status=status.HTTP_204_NO_CONTENT)
"""



from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView
from rest_framework import mixins

# 3. GenericAPIView in CBV
"""
'''
class Postlist(GenericAPIView,mixins.ListModelMixin,mixins.CreateModelMixin):
'''
class PostListCreateAPIView(ListCreateAPIView):
    queryset = Post.objects.filter(status=True)
    serializer_class = PostSerializer
    permission_classes = [IsAuthenticatedOrReadOnly]
    
'''  
class PostDetail(GenericAPIView,mixins.RetrieveModelMixin,mixins.UpdateModelMixin,mixins.DestroyModelMixin):
'''
class PostRetrieveUpdateDestroyAPIView(RetrieveUpdateDestroyAPIView):
    queryset = Post.objects.filter(status=True)
    serializer_class = PostSerializer
    permission_classes = [IsAuthenticatedOrReadOnly]
"""
    

from rest_framework import viewsets


# 4. ModelViewSet in CBV
# 4.1 viewsets.ViewSet
"""
class PostViewSet(viewsets.ViewSet):
    queryset = Post.objects.filter(status=True)
    serializer_class = PostSerializer
    permission_classes = [IsAuthenticatedOrReadOnly]
    
    def list(self,request):
        posts = self.queryset
        serializer = self.serializer_class(posts, many=True)
        return Response(serializer.data)
    
    def create(self,request):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data,status=status.HTTP_201_CREATED)
    
    def retrieve(self,request,pk=None):
        post = get_object_or_404(self.queryset, pk=pk)
        serializer = self.serializer_class(post)
        return Response(serializer.data)    
    
    def update(self,request,pk=None):
        post = get_object_or_404(self.queryset, pk=pk)
        serializer = self.serializer_class(post,data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)
    
    def partial_update(self,request,pk=None):
        post = get_object_or_404(self.queryset, pk=pk)
        serializer = self.serializer_class(post,data=request.data,partial=True)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)
    
    def destroy(self,request,pk=None):
        post = get_object_or_404(self.queryset, pk=pk)
        post.delete()
        return Response({'details':'The item successfully deleted.'},status=status.HTTP_204_NO_CONTENT)
"""


from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter ,OrderingFilter
from rest_framework.decorators import action
from .paginations import CustomPagination
from .permissions import IsOwnerOrReadOnly
# from .filters import PostFilter


# 4.2 viewsets.ModelViewSet (Router Structure)

class PostModelViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.filter(status=True)
    serializer_class = PostSerializer
    permission_classes = [IsAuthenticatedOrReadOnly,IsOwnerOrReadOnly]
    filter_backends = [DjangoFilterBackend,SearchFilter,OrderingFilter]
    # filterset_classes = PostFilter
    filterset_fields = ['author','topic','category','status']
    search_fields = ['title','content']
    ordering_fields = ['published_date','counted_views']
    pagination_class = CustomPagination
    
    @action(detail=False, methods=['get'])
    def latest_posts(self, request):
        latest_posts = self.queryset.order_by('-published_date')[:2]
        serializer = self.serializer_class(latest_posts, many=True, context={'request':request})
        return Response(serializer.data)
    
    @action(detail=True, methods=['get'])
    def latest_post(self, request, pk=None):
        latest_post = self.queryset.order_by('-published_date')[:2]
        serializer = self.serializer_class(latest_post, many=True, context={'request': request})
        return Response(serializer.data)
    
    @action(detail=True, methods=['get'])
    def most_views(self, request, pk=None):
        most_views = self.queryset.order_by('-counted_views')[:2]
        serializer = self.serializer_class(most_views, many=True, context={'request':request})
        return Response(serializer.data)
    
    @action(detail=True, methods=['get'])
    def posts_author(self, request, pk=None):
        posts_author = self.queryset.filter(author=pk)
        serializer = self.serializer_class(posts_author, many=True, context={'request':request})
        return Response(serializer.data)
    
    @action(detail=True, methods=['get'])
    def posts_category(self, request, pk=None):
        posts_category = self.queryset.filter(category=pk)
        serializer = self.serializer_class(posts_category, many=True, context={'request':request})
        return Response(serializer.data)
    
    @action(detail=True, methods=['get'])
    def posts_topic(self, request, pk=None):
        posts_topic = self.queryset.filter(topic=pk)
        serializer = self.serializer_class(posts_topic, many=True, context={'request':request})
        return Response(serializer.data)
    
   
class PostCommentModelViewSet(viewsets.ModelViewSet):
    queryset = PostComment.objects.all()
    serializer_class = PostCommentSerializer
    permission_classes = [IsAuthenticatedOrReadOnly,IsOwnerOrReadOnly]
    
    
    
    
    
    # def get_queryset(self):
    #     return self.queryset.filter(author=self.request.user)
    
    # def perform_create(self, serializer):
    #     serializer.save(author=self.request.user)
    
    # def get_permissions(self):
    #     if self.action == 'create':
    #         permission_classes = [IsAuthenticated]
    #     elif self.action in ['update','partial_update','destroy']:
    #         permission_classes = [IsAuthenticated]
    #     else:
    #         permission_classes = [IsAuthenticatedOrReadOnly]
    #     return [permission() for permission in permission_classes]
    
    # def get_serializer_class(self):
    #     if self.action == 'list':
    #         return PostSerializer
    #     elif self.action == 'retrieve':
    #         return PostSerializer
    #     return PostSerializer


class CategoryModelViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticatedOrReadOnly]
    serializer_class = CategorySerializer
    queryset = Category.objects.all()

core/templates/blog/footer.html
{% load static %}
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-7">
                <div class="widget">
                    <div class="footer-text text-left">
                        <a href="index.html"><img src="images/version/tech-footer-logo.png" alt="" class="img-fluid"></a>
                        <p>itmeter یک وبلاگ فناوری است که ما مقالات بازاریابی، اخبار و ابزار را به اشتراک می گذاریم.</p>
                        <div class="social">
                            <a href="#" data-toggle="tooltip" data-placement="bottom" title="Facebook"><i class="fa fa-facebook"></i></a>              
                            <a href="#" data-toggle="tooltip" data-placement="bottom" title="Twitter"><i class="fa fa-twitter"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="bottom" title="Instagram"><i class="fa fa-instagram"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="bottom" title="Google Plus"><i class="fa fa-google-plus"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="bottom" title="Pinterest"><i class="fa fa-pinterest"></i></a>
                        </div>

                        <hr class="invis">

                        <div class="newsletter-widget text-left">
                            <form class="form-inline">
                                <input type="text" class="form-control" placeholder="Enter your email address">
                                <button type="submit" class="btn btn-primary">ارسال کنید</button>
                            </form>
                        </div><!-- end newsletter -->
                    </div><!-- end footer-text -->
                </div><!-- end widget -->
            </div><!-- end col -->

            <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12">
                <div class="widget">
                    <h2 class="widget-title">دسته بندی های محبوب</h2>
                    <div class="link-widget">
                        <ul>
                            <li><a href="#">بازاریابی <span>(21)</span></a></li>
                            <li><a href="#">SEO سرویس <span>(15)</span></a></li>
                            <li><a href="#">آژانس دیجیتال <span>(31)</span></a></li>
                            <li><a href="#">کسب درآمد <span>(22)</span></a></li>
                            <li><a href="#">وبلاگ نویسی <span>(66)</span></a></li>
                        </ul>
                    </div><!-- end link-widget -->
                </div><!-- end widget -->
            </div><!-- end col -->

            <div class="col-lg-2 col-md-12 col-sm-12 col-xs-12">
                <div class="widget">
                    <h2 class="widget-title">حق چاپ</h2>
                    <div class="link-widget">
                        <ul>
                            <li><a href="#">درباره ما</a></li>
                            <li><a href="#">تبلیغات</a></li>
                            <li><a href="#">برای ما بنویس</a></li>
                            <li><a href="#">علامت تجاری</a></li>
                            <li><a href="#">مجوز و راهنما</a></li>
                        </ul>
                    </div><!-- end link-widget -->
                </div><!-- end widget -->
            </div><!-- end col -->
        </div>

        <div class="row">
            <div class="col-md-12 text-center">
                <br>
                <div class="copyright">&copy; itmeter. طراحی: <a href="http://html.design">ITMETER</a>.</div>
            </div>
        </div>
    </div><!-- end container -->
</footer><!-- end footer -->

core/templates/blog/header-posts.html
{% load static %}
{% if posts|length > 2 %}
<section class="section first-section">
    <div class="container-fluid">
        <div class="masonry-blog clearfix">
            {% for post in posts %}
                {% if forloop.counter == 1 %}
                    <div class="first-slot d-none d-md-block">
                        <div class="masonry-box post-media">
                            <img src="{{ post.image.url }}" alt="" class="img-fluid">
                            <div class="shadoweffect">
                                <div class="shadow-desc">
                                    <div class="blog-meta">
                                      <!--<span class="bg-orange"><a href="blog.html" title="">{{post.topic}}</a></span>-->
                                        <h4><a href="{% url 'blog:post-detail' pk=post.id %}" title="">{{post.title}}</a></h4>
                                        <small><a href="{% url 'blog:post-detail' pk=post.id %}" title="">{{post.published_date|date:"d D m Y"}}</a></small>
                                        <small><a href="author.html" title="">{{post.author.first_name}} {{post.author.last_name}}</a></small>
                                    </div><!-- end meta -->
                                </div><!-- end shadow-desc -->
                            </div><!-- end shadow -->
                        </div><!-- end post-media -->
                    </div><!-- end first-side -->
                {% endif %} 
                {% if forloop.counter == 2 or forloop.counter == 3 %}
                    <div class="second-slot">
                        <div class="masonry-box post-media">
                            <img src="{{ post.image.url }}" alt="" class="img-fluid">
                            <div class="shadoweffect">
                                <div class="shadow-desc">
                                    <div class="blog-meta">
                                    <!--<span class="bg-orange"><a href="blog.html" title="">{{post.topic}}</a></span>-->
                                        <h4><a href="{% url 'blog:post-detail' pk=post.id %}" title="">{{post.title}}</a></h4>
                                        <small><a href="{% url 'blog:post-detail' pk=post.id %}" title="">{{post.published_date|date:"d D m Y"}}</a></small>
                                        <small><a href="author.html" title="">{{post.author.first_name}} {{post.author.last_name}}</a></small>
                                    </div><!-- end meta -->
                                </div><!-- end shadow-desc -->
                            </div><!-- end shadow -->
                        </div><!-- end post-media -->
                    </div><!-- end second-side -->
                {% endif %} 
            {% endfor %}
        </div><!-- end masonry -->
    </div>
</section>
{% endif %}

core/templates/blog/org_post_header.html
<section class="section first-section">
            <div class="container-fluid">
                <div class="masonry-blog clearfix">
                    <div class="first-slot">
                        <div class="masonry-box post-media">
                             <img src="{% static 'upload/tech_01.jpg' %}" alt="" class="img-fluid">
                             <div class="shadoweffect">
                                <div class="shadow-desc">
                                    <div class="blog-meta">
                                        <span class="bg-orange"><a href="tech-category-01.html" title="">تکنولوژی</a></span>
                                        <h4><a href="tech-single.html" title="">به مبلمان اداری دست ساز واقعی سلام کنید! طراحی تمیز و زیبا</a></h4>
                                        <small><a href="tech-single.html" title="">1403 بهمن 23</a></small>
                                        <small><a href="tech-author.html" title="">توسط سهیل</a></small>
                                    </div><!-- end meta -->
                                </div><!-- end shadow-desc -->
                            </div><!-- end shadow -->
                        </div><!-- end post-media -->
                    </div><!-- end first-side -->

                    <div class="second-slot">
                        <div class="masonry-box post-media">
                             <img src="{% static 'upload/tech_02.jpg' %}" alt="" class="img-fluid">
                             <div class="shadoweffect">
                                <div class="shadow-desc">
                                    <div class="blog-meta">
                                        <span class="bg-orange"><a href="tech-category-01.html" title="">گجت ها</a></span>
                                        <h4><a href="tech-single.html" title="">هنگام انتخاب میزبانی وب اشتباه نکنید</a></h4>
                                        <small><a href="tech-single.html" title="">1403 بهمن 23</a></small>
                                        <small><a href="tech-author.html" title="">توسط سارا</a></small>
                                    </div><!-- end meta -->
                                </div><!-- end shadow-desc -->
                             </div><!-- end shadow -->
                        </div><!-- end post-media -->
                    </div><!-- end second-side -->

                    <div class="last-slot">
                        <div class="masonry-box post-media">
                             <img src="{% static 'upload/tech_03.jpg' %}" alt="" class="img-fluid">
                             <div class="shadoweffect">
                                <div class="shadow-desc">
                                    <div class="blog-meta">
                                        <span class="bg-orange"><a href="tech-category-01.html" title="">تکنولوژی</a></span>
                                        <h4><a href="tech-single.html" title="">قابل اعتمادترین تصاویر گلکسی نوت 8 لو رفت</a></h4>
                                        <small><a href="tech-single.html" title="">1403 بهمن 23</a></small>
                                        <small><a href="tech-author.html" title="">توسط سارا</a></small>
                                    </div><!-- end meta -->
                                </div><!-- end shadow-desc -->
                             </div><!-- end shadow -->
                        </div><!-- end post-media -->
                    </div><!-- end second-side -->
                </div><!-- end masonry -->
            </div>
        </section>

core/templates/blog/post_confirm_delete.html
<form method="post">{% csrf_token %}
    <p class="d-flex justify-content-center align-items-center  pt-2 pb-3">Are you sure you want to delete ? </p>
    <p class="d-flex justify-content-center align-items-center  pt-2 pb-3">"{{ object }}"</p>
    {{ form }}

    <div class="d-flex justify-content-center align-items-center rounded-4 pt-2 pb-3">
        <input class="btn btn-danger" type="submit" value="Confirm">
    </div>
</form>

core/templates/blog/post_form.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Post</title>
    <link rel="stylesheet" href="{% static 'css/version/style.css' %}"> <!-- Link to your CSS file -->
</head>
<body>
    <div class="container mt-5 mb-5 text-center post-form">
        <h1>Create a New Post</h1>
        <form method="post" enctype="multipart/form-data"> 
            {% csrf_token %}
            {{ form.as_p }} 
            <button type="submit" class="btn btn-primary">Submit Post</button>
        </form>
        <a href="{% url 'blog:post_list' %}">Back to Posts</a>  <!-- Link to go back to the post list -->
    </div>
</body>
</html>

core/templates/blog/test.html
<form class="form-wrapper">
                {% csrf_token %}
                <input type="text" class="form-control" placeholder="Your first_name last_name">
                <input type="text" class="form-control" placeholder="Email address">
                <textarea class="form-control" placeholder="Your comment"></textarea>
                <button type="submit" class="btn btn-primary">send your comment</button>
            </form>



            <div class="form-group">
                <label for="id_name">Name</label>
                <input type="text" id="id_name" name="name" class="form-control" placeholder="Your first_name last_name" value="{{ form.name.value|default_if_none:'' }}" readonly>
            </div>

            <div class="form-group">
                <label for="id_email">Email</label>
                <input type="email" id="id_email" name="email" class="form-control" placeholder="Email address" value="{{ form.email.value|default_if_none:'' }}" readonly>
            </div>

            <div class="form-group">
                <label for="id_subject">Subject</label>
                <input type="text" id="id_subject" name="subject" class="form-control" placeholder="Your subject" value="{{ form.subject.value|default_if_none:'' }}">
            </div>

            <div class="form-group">
                <label for="id_message">Comment</label>
                <textarea id="id_message" name="message" class="form-control" placeholder="Your comment">{{ form.message.value|default_if_none:'' }}</textarea>
            </div>


            <form class="form-wrapper" method="post">
                {% csrf_token %}
                <div>
                    <label for="{{ form.subject.id_for_label }}">Subject:</label>
                    <input type="text" name="subject" id="{{ form.subject.id_for_label }}" value="{{ form.subject.value|default:'' }}" required>
                </div>
                <div>
                    <label for="{{ form.message.id_for_label }}">Message:</label>
                    <textarea name="message" id="{{ form.message.id_for_label }}" required>{{ form.message.value|default:'' }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">Send your comment</button>
            </form>